
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: postgres
      DB_HOST: localhost
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back:
    build: ./back
    ports:
      - "8080:8080"
    depends_on:
      - db
  front:
    build: ./front
    ports:
      - "3000:80"
    depends_on:
      - back

  pinger:
    build: ./pinger
    depends_on:
      - back
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:latest
    ports:
      - "90:90"
    volumes:
      - ./front/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front
      - back

volumes:
  postgres_data: