
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe230405180405
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back:
    build: ./back
    ports:
      - "8090:8080"
    depends_on:
      - db
  front:
    build: ./front
    ports:
      - "3000:80"
    depends_on:
      - back

  pinger:
    build: ./pinger
    depends_on:
      - back
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx
    ports:
      - "880:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front
      - back

volumes:
  postgres_data: